project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Shaela Noble"
  repo-url: https://github.com/shaela-noble/shaela-noble.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right: 
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/shaela-noble/shaela-noble.github.io
  page-footer: 
    center: "Copyright &copy; 2026, Shaela Noble"
    background: secondary

format:
  html:
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false